title: Hello, I'm Nadaa
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Nadaa Shabrina. I am a student at UIN SUSKA Riau. I am interested in many things! 
permalink: ':title/'
baseurl: "/nadasabs-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/nadasabs #if your site has a twitter account, enter it here

# Author Settings
author: Nadaa Shabrina # add your name
author-img: nadasabs.jpg # add your photo
about-author: I am a student at UIN SUSKA Riau. In this blog I will 
  share you about the things that I am interested in. Please enjoy! # add description
social-twitter: nadasabs # add your Twitter handle
social-facebook: nadasabs # add your Facebook handle
social-github: nadasabs # add your Github handle
social-linkedin: nadasabs # add your Linkedin handle
social-email: anadaasb@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
